export { default as FavoritesIcon } from './favorites.svg'
export { default as ComparisonIcon } from './comparison.svg'
export { default as CartIcon } from './cart.svg'
export { default as ProfileIcon } from './profile.svg'
export { default as SearchIcon } from './search.svg'
export { default as LogoIcon } from './logo.svg'
export { default as BurgerIcon } from './burger.svg'